apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: myapp
    replica: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
